[secrets]  # Main section (required)
GEMINI_API_KEY = "AIzaSyD5UylBUOnioaEO9yuLXz5Xx-SgnBuxT_g"  # Your Gemini key
MONGO_URI = "mongodb+srv://oxo_ai:uKYo6xRy1SOpirjM@cluster-ai-recruitment.ygmwer8.mongodb.net/?retryWrites=true&w=majority"
DEBUG = "False"  # Must be string in TOML
LOG_LEVEL = "INFO"